version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/test/conf.d:/etc/nginx/conf.d
      - ./nginx/test/ssl:/etc/nginx/ssl
      - ./nginx/test/certbot/conf:/etc/letsencrypt
      - ./nginx/test/certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - test-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/test/certbot/conf:/etc/letsencrypt
      - ./nginx/test/certbot/www:/var/www/certbot
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - .env.test
    volumes:
      - ./backend/app:/app/app
      - ./logs/test:/app/logs
    depends_on:
      - db
      - mongodb
    networks:
      - test-network
    restart: unless-stopped

  db:
    image: postgres:13
    env_file:
      - .env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - test-network
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_test_data:/data/db
    expose:
      - "27017"
    networks:
      - test-network
    restart: unless-stopped

networks:
  test-network:
    driver: bridge

volumes:
  postgres_test_data:
  mongodb_test_data:
